# Generated by Django 6.0.5 on 2026-05-29 07:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("story_intro", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "module_type",
                    models.IntegerField(
                        choices=[
                            (1, "方向指令模組"),
                            (2, "指定高度模組"),
                            (3, "調頻模組"),
                            (4, "RGB模組"),
                            (5, "摩斯密碼模組"),
                            (6, "旋鈕模組"),
                            (7, "密碼模組"),
                            (8, "拆線模組"),
                            (9, "符號指撥開關模組"),
                        ]
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "time_limit",
                    models.PositiveIntegerField(
                        default=60, help_text="Time limit in seconds"
                    ),
                ),
                (
                    "story_text",
                    models.TextField(
                        blank=True, help_text="Story context for this module", null=True
                    ),
                ),
                (
                    "config_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="JSON data containing the answers/config for the module",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="mainapp.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.DeleteModel(
            name="SensorData",
        ),
    ]
