# Generated by Django 4.2.30 on 2026-06-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(help_text="MQTT Topic", max_length=255)),
                (
                    "value",
                    models.CharField(
                        help_text="Sensor Value (String/JSON)", max_length=512
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, help_text="Time received"),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
